languages:
  Ruby: true
engines:
  rubocop:
    enabled: false
  fixme:
    enabled: false
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
exclude_paths: [db/migrate/schema.db]
