Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/ModuleLength:
  Exclude:
    - 'spec/controllers/**/*.rb'

AllCops:
  Exclude:
    - 'Gemfile.lock'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'lib/templates/**/*'
    - 'config/initializers/**/*'
    - '*file'

  RunRailsCops: true
