default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: 'dba'
  password: 'admin'
  pool: 5

development:
  <<: *default
  database: zueira_development

test:
  <<: *default
  database: zueira_test
